extends: "react-app"

globals:
  __dirname: false
  graphql: false
  process: false
  TimelineLite: false
  TimelineMax: false
  TweenLite: false
  TweenMax: false

plugins:
- react-hooks

rules:
  import/first: 'off'
  no-use-before-define: 'off'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
